on:
  workflow_dispatch:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master"]}

env:
  GH_PUB_KEY:
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
  GH_BOT_ACC_EMAIL:
    41898282+github-actions[bot]@users.noreply.github.com
  GH_BOT_ACC_NAME:
    github-actions[bot]

jobs:
  readme-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          Submodules: 'submodule-repo'

      - name: setup git
        run: |
          git config --local user.email $GH_BOT_ACC_EMAIL
          git config --local user.name $GH_BOT_ACC_NAME

      - uses: actions/setup-python@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          python-version: '3.x'
          architecture: 'x64'

      - name: install requirements
        run: pip install -r requirements.txt

      - name: running script
        run: python generate.py

      - name: Commit files
        run: |
          git add .
          git commit -m "Update README.md (bot)" || echo "No change to commit."
          git push || echo "Skipped push."

