# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * 0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Sigmanificient
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          plugin_languages: yes
          plugin_languages_analysis_timeout: 50
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 32
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 100
          plugin_languages_recent_load: 3000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
